// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[...path].ts";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/api/add-game/from-github.ts";
import * as $4 from "./routes/api/add-game/from-url.ts";
import * as $5 from "./routes/api/add-game/from-zip.ts";
import * as $6 from "./routes/api/games.ts";
import * as $7 from "./routes/api/games/[id]/index.ts";
import * as $8 from "./routes/api/games/[id]/thumbnail.ts";
import * as $9 from "./routes/api/games/[id]/update.ts";
import * as $10 from "./routes/api/games/[id]/recommended-buttons.ts";
import * as $11 from "./routes/api/heartbeat.ts";
import * as $12 from "./routes/index.ts";

const manifest = {
  routes: {
    "./routes/[...path].ts": $0,
    "./routes/_404.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/api/add-game/from-github.ts": $3,
    "./routes/api/add-game/from-url.ts": $4,
    "./routes/api/add-game/from-zip.ts": $5,
    "./routes/api/games.ts": $6,
    "./routes/api/games/[id]/index.ts": $7,
    "./routes/api/games/[id]/thumbnail.ts": $8,
    "./routes/api/games/[id]/update.ts": $9,
    "./routes/api/games/[id]/recommended-buttons.ts": $10,
    "./routes/api/heartbeat.ts": $11,
    "./routes/index.ts": $12,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
